# Generated by Django 2.1.5 on 2019-08-25 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('picture', models.TextField()),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpotPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('profile_picture', models.TextField(null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.TextField(null=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('sns_token', models.CharField(max_length=100, null=True, unique=True)),
                ('is_push', models.BooleanField(default=True)),
                ('login_type', models.IntegerField()),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='after_noon',
            field=models.ManyToManyField(related_name='after_noon', to='api.Spot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='morning',
            field=models.ManyToManyField(related_name='morning', to='api.Spot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='night',
            field=models.ManyToManyField(related_name='night', to='api.Spot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Spot'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Spot'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User'),
        ),
    ]
