# Generated by Django 2.2.4 on 2019-09-01 12:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190901_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=api.models.user_profile_upload),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
