# Generated by Django 2.1.5 on 2019-09-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190905_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='order',
        ),
    ]
