# Generated by Django 2.1.5 on 2019-09-05 13:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190905_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotpicture',
            name='url',
        ),
        migrations.AddField(
            model_name='spotpicture',
            name='picture',
            field=models.ImageField(null=True, upload_to=api.models.user_profile_upload),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=api.models.user_profile_upload),
        ),
    ]
