# Generated by Django 2.1.5 on 2019-09-08 07:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190905_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spotpicture',
            name='picture',
            field=models.ImageField(null=True, upload_to=api.models.spot_image_upload),
        ),
    ]
