# Generated by Django 2.2.4 on 2019-09-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tag_tagitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.Spot'),
        ),
        migrations.AlterField(
            model_name='like',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='api.Spot'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='api.Spot'),
        ),
    ]
