# Generated by Django 2.2.4 on 2019-09-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190914_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Spot'),
        ),
        migrations.AlterField(
            model_name='like',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.Spot'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.Spot'),
        ),
    ]
