# Generated by Django 2.2.4 on 2019-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190915_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='gu',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
