# Generated by Django 2.2.4 on 2019-09-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190921_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='content',
            new_name='en_content',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='district',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='name',
        ),
        migrations.AddField(
            model_name='spot',
            name='en_address',
            field=models.CharField(default='seoul', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='en_name',
            field=models.CharField(default='Namsan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='en_operation',
            field=models.CharField(default='12:00~13:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='en_subway',
            field=models.CharField(default='SAMSUNG', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='homepage',
            field=models.CharField(default='http://121212.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='kr_address',
            field=models.CharField(default='서울', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='kr_content',
            field=models.TextField(default='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='kr_name',
            field=models.CharField(default='남산', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='kr_operation',
            field=models.CharField(default='12:00~13:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='kr_subway',
            field=models.CharField(default='삼성', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='line',
            field=models.CharField(default=0.5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='phone',
            field=models.CharField(default='01066555744', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='recommend_time',
            field=models.CharField(default='12:00-13:00', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spot',
            name='gu',
            field=models.IntegerField(default=0),
        ),
    ]
