# Generated by Django 2.2.4 on 2019-09-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190921_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.Spot')),
            ],
        ),
        migrations.RemoveField(
            model_name='tagitem',
            name='bundle',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagItem',
        ),
    ]
