# Generated by Django 2.2.4 on 2019-09-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190922_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='en_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='kr_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
